[project]
name = 'DeadManSwitch'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.asset-manager]
path = 'contracts/asset-manager.clar'
clarity_version = 2
epoch = 2.5

[contracts.dead-mans-switch]
path = 'contracts/dead-mans-switch.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
